# 端口设置
server:
  port: 8081
spring:
  application:
    name: item-service

  rabbitmq:
    host: 10.211.55.4
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: leyou.item.exchange
    publisher-confirms: true # 生产者确认机制，确保消息会正确发送 [ 如果发送失败会有错误回执，从而触发重试 ]
  # 数据信息
  datasource:
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
eureka:
# 默认地址
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
# 实例心跳时间
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
# MyBatis 别名扫描
mybatis:
  type-aliases-package: com.leyou.item.pojo
